"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 21:39:40.488548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gardens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_label', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('climate_zone', sa.String(length=120), nullable=False),
    sa.Column('map_width_m', sa.Float(), nullable=False),
    sa.Column('map_height_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gardens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gardens_owner_id'), ['owner_id'], unique=False)

    op.create_table('garden_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('parent_area_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area_type', sa.String(length=20), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['parent_area_id'], ['garden_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garden_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garden_areas_garden_id'), ['garden_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garden_areas_parent_area_id'), ['parent_area_id'], unique=False)

    op.create_table('garden_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_garden_chat_message_role'),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garden_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garden_chat_messages_garden_id'), ['garden_id'], unique=False)

    op.create_table('plantings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('crop_variety_id', sa.Integer(), nullable=True),
    sa.Column('crop_name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=20), nullable=False),
    sa.Column('growth_stage', sa.String(length=60), nullable=True),
    sa.Column('planted_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plantings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantings_garden_id'), ['garden_id'], unique=False)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('container_type', sa.String(length=20), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('volume_liters', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_area_id'], ['garden_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_garden_area_id'), ['garden_area_id'], unique=False)

    op.create_table('garden_ai_loop_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('transcript_path', sa.String(length=255), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['garden_chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    with op.batch_alter_table('garden_ai_loop_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garden_ai_loop_runs_garden_id'), ['garden_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garden_ai_loop_runs_message_id'), ['message_id'], unique=False)

    op.create_table('planting_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=False),
    sa.Column('garden_area_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(garden_area_id IS NOT NULL) != (container_id IS NOT NULL)', name='exactly_one_of_area_or_container'),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['garden_area_id'], ['garden_areas.id'], ),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planting_id')
    )
    with op.batch_alter_table('planting_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planting_locations_container_id'), ['container_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planting_locations_garden_area_id'), ['garden_area_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_locations_garden_area_id'))
        batch_op.drop_index(batch_op.f('ix_planting_locations_container_id'))

    op.drop_table('planting_locations')
    with op.batch_alter_table('garden_ai_loop_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garden_ai_loop_runs_message_id'))
        batch_op.drop_index(batch_op.f('ix_garden_ai_loop_runs_garden_id'))

    op.drop_table('garden_ai_loop_runs')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_garden_area_id'))

    op.drop_table('containers')
    with op.batch_alter_table('plantings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantings_garden_id'))

    op.drop_table('plantings')
    with op.batch_alter_table('garden_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garden_chat_messages_garden_id'))

    op.drop_table('garden_chat_messages')
    with op.batch_alter_table('garden_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garden_areas_parent_area_id'))
        batch_op.drop_index(batch_op.f('ix_garden_areas_garden_id'))

    op.drop_table('garden_areas')
    with op.batch_alter_table('gardens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gardens_owner_id'))

    op.drop_table('gardens')
    # ### end Alembic commands ###
