"""Assessment loop runs: the Perceive → Reason → Act → Observe → Repeat trace per assessment.

One row per assessment (deleted with it), holding the run id, reviewer model,
iteration count, verdict and the full phase trace shown on the record page.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_loop_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer_model', sa.String(length=120), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('transcript_path', sa.String(length=255), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_assessment_loop_runs_run_id')
    )
    with op.batch_alter_table('assessment_loop_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_loop_runs_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_loop_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_loop_runs_assessment_id'))

    op.drop_table('assessment_loop_runs')
    # ### end Alembic commands ###
