"""Baseline of the existing Almanac schema."""

from alembic import op
import sqlalchemy as sa

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_slugs", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_ai_chat_message_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_chat_messages_session_id"), "ai_chat_messages", ["session_id"], unique=False
    )
    op.create_table(
        "plant_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("common_name", sa.String(length=120), nullable=False),
        sa.Column("scientific_name", sa.String(length=160), nullable=False),
        sa.Column("family", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plant_references_common_name"), "plant_references", ["common_name"], unique=False
    )
    op.create_index(op.f("ix_plant_references_slug"), "plant_references", ["slug"], unique=True)
    op.create_table(
        "ai_loop_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_key", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("final_answer", sa.Text(), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("transcript_path", sa.String(length=255), nullable=False),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["ai_chat_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_ai_loop_runs_message_id"), "ai_loop_runs", ["message_id"], unique=False
    )
    op.create_index(op.f("ix_ai_loop_runs_owner_key"), "ai_loop_runs", ["owner_key"], unique=False)
    op.create_table(
        "plant_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_reference_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["plant_reference_id"], ["plant_references.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
        sa.UniqueConstraint("plant_reference_id"),
    )
    op.create_table(
        "planting_months",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_reference_id", sa.Integer(), nullable=False),
        sa.Column("month_number", sa.Integer(), nullable=False),
        sa.CheckConstraint("month_number BETWEEN 1 AND 12", name="ck_planting_months_month_number"),
        sa.ForeignKeyConstraint(
            ["plant_reference_id"], ["plant_references.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plant_reference_id", "month_number"),
    )
    op.create_index(
        op.f("ix_planting_months_plant_reference_id"),
        "planting_months",
        ["plant_reference_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Baseline downgrade is destructive; restore a backup instead.")
