"""Nullable planning fields and normalized plant knowledge."""

from alembic import op
import sqlalchemy as sa

revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diseases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "function_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "rotation_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column(
            "feeder_weight",
            sa.Enum(
                "light",
                "medium",
                "heavy",
                name="feeder_weight",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_rotation_exempt", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "uses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "plant_companions",
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("companion_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("plant_id != companion_id", name="ck_companion_not_self"),
        sa.ForeignKeyConstraint(["companion_id"], ["plant_references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["function_tags.id"],
        ),
        sa.ForeignKeyConstraint(["plant_id"], ["plant_references.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plant_id", "companion_id", "function_id"),
    )
    op.create_table(
        "plant_diseases",
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plant_references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["diseases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plant_id", "tag_id"),
    )
    op.create_table(
        "plant_function_tags",
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plant_references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["function_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plant_id", "tag_id"),
    )
    op.create_table(
        "plant_pests",
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plant_references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["pests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plant_id", "tag_id"),
    )
    op.create_table(
        "plant_uses",
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plant_references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["uses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plant_id", "tag_id"),
    )
    with op.batch_alter_table("plant_references", schema=None) as batch_op:
        batch_op.add_column(sa.Column("yield_qty", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("in_row_spacing_cm", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("row_spacing_cm", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("succession_interval_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("harvest_window_weeks", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("soil_ph_min", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("soil_ph_max", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("yield_wording", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("yield_unit", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("management_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("care_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("uses_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("sowing_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("source_url", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("notion_url", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "feeder_type",
                sa.Enum(
                    "heavy feeder",
                    "light feeder",
                    "nitrogen fixer",
                    name="feeder_type",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "water_needs",
                sa.Enum(
                    "low",
                    "moderate",
                    "high",
                    name="water_needs",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "sun_needs",
                sa.Enum(
                    "full sun",
                    "part shade",
                    "shade",
                    name="sun_needs",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "forest_layer",
                sa.Enum(
                    "canopy",
                    "sub-canopy",
                    "shrub",
                    "herbaceous",
                    "rhizosphere",
                    "groundcover",
                    "vine",
                    name="forest_layer",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "part_used",
                sa.Enum(
                    "leaf",
                    "root",
                    "fruit",
                    "flower",
                    "bark",
                    "seed",
                    name="part_used",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("rotation_group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_plant_rotation_group", "rotation_groups", ["rotation_group_id"], ["id"]
        )

        batch_op.create_check_constraint(
            "ck_harvest_window_weeks_positive", "harvest_window_weeks > 0"
        )
        batch_op.create_check_constraint("ck_ph_min", "soil_ph_min BETWEEN 0 AND 14")
        batch_op.create_check_constraint("ck_ph_order", "soil_ph_min <= soil_ph_max")
        batch_op.create_check_constraint(
            "ck_succession_interval_days_positive", "succession_interval_days > 0"
        )
        batch_op.create_check_constraint("ck_in_row_spacing_cm_positive", "in_row_spacing_cm > 0")
        batch_op.create_check_constraint(
            "ck_yield_pair",
            "(yield_qty IS NULL AND yield_unit IS NULL) OR (yield_qty IS NOT NULL AND yield_unit IS NOT NULL)",
        )
        batch_op.create_check_constraint("ck_ph_max", "soil_ph_max BETWEEN 0 AND 14")
        batch_op.create_check_constraint("ck_row_spacing_cm_positive", "row_spacing_cm > 0")
        batch_op.create_check_constraint("ck_yield_qty_positive", "yield_qty > 0")

    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Restore a database backup to undo this data-bearing migration.")
